version: "3.8"

services:
  app:
    build:
      context: ./Aplicacao
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PGDB=Host=postgresdb;Port=5432;Database=postgres;Password=123;
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    container_name: postgresDb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
